/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type { IKlerosGTCR, IKlerosGTCRInterface } from "../IKlerosGTCR";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "bytes32",
        name: "_itemID",
        type: "bytes32",
      },
      {
        indexed: true,
        internalType: "address",
        name: "_submitter",
        type: "address",
      },
      {
        indexed: true,
        internalType: "uint256",
        name: "_evidenceGroupID",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "bytes",
        name: "_data",
        type: "bytes",
      },
    ],
    name: "ItemSubmitted",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint256",
        name: "_metaEvidenceID",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "string",
        name: "_evidence",
        type: "string",
      },
    ],
    name: "MetaEvidence",
    type: "event",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "_itemID",
        type: "bytes32",
      },
    ],
    name: "getItemInfo",
    outputs: [
      {
        internalType: "bytes",
        name: "",
        type: "bytes",
      },
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class IKlerosGTCR__factory {
  static readonly abi = _abi;
  static createInterface(): IKlerosGTCRInterface {
    return new utils.Interface(_abi) as IKlerosGTCRInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IKlerosGTCR {
    return new Contract(address, _abi, signerOrProvider) as IKlerosGTCR;
  }
}
