/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type { IUserRegistry, IUserRegistryInterface } from "../IUserRegistry";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "_user",
        type: "address",
      },
    ],
    name: "isVerifiedUser",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class IUserRegistry__factory {
  static readonly abi = _abi;
  static createInterface(): IUserRegistryInterface {
    return new utils.Interface(_abi) as IUserRegistryInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IUserRegistry {
    return new Contract(address, _abi, signerOrProvider) as IUserRegistry;
  }
}
